#
# Copyright (c) 2021 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
server:
  port: 8080
opentracing:
  jaeger:
    service-name: Users
    udp-sender:
      host: jaeger-agent
      port: 5775
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  jackson:
    default-property-inclusion: non_null
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
logging:
  level:
    root: warn
    "Coherence": info
    org.springframework.security: debug
    org.springframework.web: info
    com.oracle.coherence.spring: info
