#
# Copyright (c) 2021, 2022 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
server:
  port: ${port:8083}
spring:
  application:
    name: Orders
management:
  tracing:
    enabled: false
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://jaeger-agent:9411/api/v2/spans
      # endpoint: http://127.0.0.1:9411/api/v2/spans # Zipkin & Jaeger
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
logging:
  level:
    root: warn
    "Coherence": info
    org.springframework: info
    org.springframework.web: info
    com.oracle.coherence.spring: info
    com.oracle.coherence.examples.sockshop.spring: info
    org.apache.http: debug
feign:
  httpclient:
    enabled: true