#
# Copyright (c) 2021 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
server:
  port: ${port:8081}
spring:
  application:
    name: Shipping
  sleuth:
    propagation:
      type: B3,W3C
    opentracing:
      enabled: true
    supports-join: false
  zipkin:
    base-url: http://jaeger-agent:9411
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: warn
    "Coherence": info
    org.springframework.web: info
    com.oracle.coherence.spring: info
    org.apache.http: info # set to debug to see logging of http payloads

